services:
  auth-app:
    container_name: netology-demo-docker
    build: .
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090  # <--- Spring Boot прочитает эту переменную и сменит порт
    # Перезапуск контейнера при ошибке
    restart: unless-stopped